//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        public int Id_utilisateur { get; set; }
        public string email_utilisateur { get; set; }
        public string Nom_utilisateur { get; set; }
        public string GroupeUtilisateur { get; set; }
        public string Mot_de_passe { get; set; }
    }
}
